import { setLogout } from "@/api";
import { USER_ROLE } from "@/constants";
import { useCurrentUser } from "@/utils/hoos";
import { DownOutlined } from "@ant-design/icons";
import {
  ProfileOutlined,
  SnippetsOutlined,
  SolutionOutlined,
  UserOutlined,
} from "@ant-design/icons";
import {
  Layout as AntdLayout,
  Dropdown,
  Menu,
  MenuProps,
  Space,
  message,
} from "antd";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { PropsWithChildren, ReactElement, useMemo } from "react";

import styles from "./index.module.css";

const { Header, Sider, Content } = AntdLayout;

const ITEMS = [
  {
    label: "图书管理",
    key: "book",
    role: USER_ROLE.USER,
    icon: <SnippetsOutlined />,
    children: [
      {
        label: "图书列表",
        key: "/book",
        role: USER_ROLE.USER,
      },
      {
        label: "图书添加",
        key: "/book/add",
        role: USER_ROLE.ADMIN,
      },
    ],
  },
  {
    label: "借阅管理",
    key: "borrow",
    role: USER_ROLE.USER,
    icon: <SolutionOutlined />,
    children: [
      {
        label: "借阅列表",
        key: "/borrow",
        role: USER_ROLE.USER,
      },
      {
        label: "书籍借阅",
        key: "/borrow/add",
        role: USER_ROLE.ADMIN,
      },
    ],
  },
  {
    label: "分类管理",
    key: "/category",
    icon: <ProfileOutlined />,
    role: USER_ROLE.ADMIN,
  },
  {
    label: "用户管理",
    key: "user",
    icon: <UserOutlined />,
    role: USER_ROLE.ADMIN,
    children: [
      {
        label: "用户列表",
        key: "/user",
        role: USER_ROLE.ADMIN,
      },
      {
        label: "用户添加",
        key: "/user/add",
        role: USER_ROLE.ADMIN,
      },
    ],
  },
];

const Layout: React.FC<
  PropsWithChildren & { title?: string; operation?: ReactElement }
> = ({ children, title = "图书列表", operation }) => {
  const router = useRouter();
  const user = useCurrentUser();

  const activeMenu = router.pathname;
  const defaultOpenKeys = [activeMenu.split("/")[1]];

  const handleChangeMenu: MenuProps["onClick"] = (e) => {
    router.push(e.key);
  };

  const USER_ITEMS: MenuProps["items"] = [
    {
      key: "1",
      label: <Link href={`/user/edit/${user?._id}`}>个人中心</Link>,
    },
    {
      key: "2",
      label: (
        <span
          onClick={async () => {
            await setLogout();
            localStorage.removeItem("user");
            message.success("退出成功");
            router.push("/login");
          }}
        >
          退出
        </span>
      ),
    },
  ];

  const items = useMemo(() => {
    if (user?.role === USER_ROLE.USER) {
      return ITEMS.filter((item) => {
        if (item.children) {
          item.children = item.children.filter(
            (k) => k.role === USER_ROLE.USER
          );
        }
        return item.role === USER_ROLE.USER;
      });
    } else {
      return ITEMS;
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>图书管理</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout className={styles.container}>
          <Header className={styles.header}>
            <Image
              src="/logo.svg"
              width={30}
              height={30}
              alt="logo"
              className={styles.logo}
            />
            图书管理系统
            <span className={styles.user}>
              <Dropdown menu={{ items: USER_ITEMS }} placement="bottom">
                <span onClick={(e) => e.preventDefault()}>
                  <Space>
                    {user?.nickName}
                    <DownOutlined />
                  </Space>
                </span>
              </Dropdown>
            </span>
          </Header>
          <AntdLayout>
            <Sider className={styles.sider}>
              <Menu
                className={styles.menu}
                onClick={handleChangeMenu}
                selectedKeys={[activeMenu]}
                items={items}
                mode="inline"
                theme="light"
                defaultOpenKeys={defaultOpenKeys}
              />
            </Sider>
            <Content className={styles.content}>{children}</Content>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  );
};

export default Layout;
